[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Ortak ayarlar (Her iki sistemde de aynıdır):
upload_speed = 115200
monitor_speed = 115200

; Doğrulama aşamasını hızlı geçmek için opsiyonel bayrak:
upload_flags = -V

lib_deps = 
    arduino-libraries/Servo@^1.2.2
    miguelbalboa/MFRC522@^1.4.11
    SevSegShift
	adafruit/DHT sensor library @ ^1.4.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14
    z3t0/IRremote @ ^4.4.1